
SUPABASE_URL = "https://afmrazheevkymzmbuxan.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbXJhemhlZXZreW16bWJ1eGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTQ4MDcsImV4cCI6MjA3Njg5MDgwN30.DRCNmPTGrd8EIho99ppHtgXGvs3ql5UvuXDEtlOKykY"
SMTP_SERVER = "smtp.monfournisseur.com"
SMTP_PORT = 465
SMTP_USER = "mon.login@mail.com"
SMTP_PASSWORD = "mon_mot_de_passe"
SMTP_FROM = "everinsight@mondomaine.com"
